# Using the node alpine image to build the React app
image: node:alpine

# Announce the URL as per CRA docs
variables:
  PUBLIC_URL: /sygna/bridge/demo
# Cache node modules - speeds up future builds
cache:
  paths:
  - node_modules

# Name the stages involved in the pipeline
stages:
- deploy

# Job name for gitlab to recognise this results in assets for Gitlab Pages
pages:
  stage: deploy
  script:
    - npm install # Install all dependencies
    - unset CI
    - npm run build --prod # Build for prod
    - cp public/index.html public/404.html
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
