name: MasterDeployCI
on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        env:
          ORG_READ_REPO: ${{ secrets.ORG_READ_REPO }}
        run: |
            git config --global user.email "tech@coolbitx.com"
            git config --global user.name "cbx-tech"
            git remote set-url origin https://${ORG_READ_REPO}@github.com/CoolBitX-Technology/sygna-bridge-demo.git
            npm run deploy
